// <auto-generated />
namespace Unigo.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddLongLatToDestinations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLongLatToDestinations));
        
        string IMigrationMetadata.Id
        {
            get { return "201912061911194_AddLongLatToDestinations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
